### ISSUE TITLE
V2 extension is getting installed as a separate plugin in vscode

### ISSUE THREAD

**Issue by LakshmiMekala** [TIBCOSoftware/vscode-extension-mashling#12]
If both mashling v1 and v2 supported plugins were installed in vs-code. mashling commands are conflicting and not working as expected.

**Comment by tbhatia1912** [comment]
Issue is coming after changing publisher name as vscode identifies a package by the package id which is in format "publishername.packagename". Since we changed publisher name, it was treating it as a separate package.

Solution for now : Kept the publisher name same to make vscode autodetect the older package.

Note: To change the publisher name, one possible solution was to detect and delete the old package at the activation of new package but this doesn't seem to be working in MacOs because of vscode dependencies. I am looking for alternative solution.
